<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fex</string>
	</array>
	<key>name</key>
	<string>WebFocus</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.webfocus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.webfocus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.webfocus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.webfocus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.webfocus</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.webfocus</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>The WebFocus functions to provide information about the variables.</string>
			<key>match</key>
			<string>([\&amp;]\w*\b)([\.])((EXISTS|TYPE|LENGTH))</string>
			<key>name</key>
			<string>Variable.parameter.webfocus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|-)?[\&amp;]\w*\b</string>
			<key>name</key>
			<string>variable.language.webfocus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^-?(ACROSS|ACTUAL|ALIAS|ALL|AND|AS|BY|CASE|CENTER|CLEAR|COM(MIT|PUTE)|CONTAINS|CTRAN|DECODE|DEFINE|DISK|DOS|EDIT|END(CASE|REPEAT|SYTLE)|EXCLUDES|EXIT)\b</string>
			<key>name</key>
			<string>keyword.operator.webfocus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^-?(FIELD(NAME|TYPE)?|FILE(DEF|NAME)?|FOLD-LINE|FOOTING|FOR(MAT)?|FROM|GE(TTOK)?|GRAPH|HEADING|HOLD|IN|INCLUDE|INDEX|JOIN|LAST|LIST|LJUST|MISSING|MORE|MULTILINES)\b</string>
			<key>name</key>
			<string>keyword.operator.webfocus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^-?(NEW(-NOT-OLD)?|NO(PRINT|SPLIT)|OLD(-AND-NEW|-NOR-NEW|-NOT-NEW|-OR-NEW)?|OMITS|ON|OR|PAGE-BREAK|PCHOLD|POSIT|PRINT|RE(CAP|COMPUTE|PAGE)|RUN)\b</string>
			<key>name</key>
			<string>keyword.operator.webfocus</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.webfocus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((^-)?)(SEG(MENT|TYPE)|SET|SKIP-LINE|STYLE|SUB(-TOTAL|FOOT|HEAD|TOTAL)|SUFFIX|SUM(MARIZE)?|TABLE(F)?|TO(TAL)?|UNDER-LINE|USAGE|WHEN|WHERE)\b</string>
			<key>name</key>
			<string>keyword.operator.webfocus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|[^-])(ELSE|END|EQ|GE|GOTO|GT|IF|IS|LT|LE|NE|THEN)\b</string>
			<key>name</key>
			<string>storage.modifier.webfocus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>SQL(MSS|ORA|OUT)?|-WRITE|SERVER</string>
			<key>name</key>
			<string>support.function.webfocus</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.webfocus</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(^-\*).*$\n?</string>
					<key>name</key>
					<string>comment.line.dash-star.webfocus</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.webfocus</string>
	<key>uuid</key>
	<string>4773db26-1acb-4922-9d73-bd41662a97b5</string>
</dict>
</plist>
